language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nathanlw-2020/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nathanlw-2020/docker-react npm run test -- --coverage

